version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aegir
    versions:
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
    - 33.1.0
  - dependency-name: it-to-stream
    versions:
    - 1.0.0
  - dependency-name: it-glob
    versions:
    - 0.0.11
  - dependency-name: err-code
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: native-fetch
    versions:
    - 3.0.0
  - dependency-name: native-abort-controller
    versions:
    - 1.0.0
    - 1.0.3
  - dependency-name: delay
    versions:
    - 5.0.0
